# Generated by Django 4.0.6 on 2022-08-15 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0003_rename_product_menu_alter_menu_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=250)),
                ('email', models.EmailField(max_length=30)),
                ('message', models.TextField()),
                ('admin_note', models.TextField()),
                ('status', models.CharField(choices=[('new', 'new'), ('pending', 'pending'), ('processing', 'processing'), ('resolved', 'resolved')], default='new', max_length=50)),
                ('message_date', models.DateTimeField(auto_now_add=True)),
                ('admin_update', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Contact',
                'verbose_name_plural': 'Contact',
                'db_table': 'contact',
                'managed': True,
            },
        ),
        migrations.AlterModelTable(
            name='menu',
            table='menu',
        ),
    ]
