# Generated by Django 4.0.6 on 2022-08-15 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0004_contact_alter_menu_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='img',
            field=models.ImageField(default='prod.jpg', upload_to='menu'),
        ),
    ]
