# Generated by Django 4.0.6 on 2023-01-15 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0007_shopcart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='pix',
            field=models.ImageField(default='jeff.jpg', upload_to='profile'),
        ),
    ]
